version: '3.8'

services:
  qr-code-generator:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:80" # Map port 3000 on the host to port 80 in the container
    environment:
      - NODE_ENV=production
